name:                aoc2020
version:             0.1.0.0
github:              "CRTified/aoc2020"
license:             MIT
author:              "Carl Richard Theodor Schneider"
maintainer:          "carl.schneider+github@rub.de"
copyright:           "2020 Carl Richard Theodor Schneider"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2020#readme>

dependencies:
- base >= 4.7 && < 5
- criterion

library:
  source-dirs: src

executables:
  aoc2020-day1:
    main:                Day1.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
    - criterion
  aoc2020-day2:
    main:                Day2.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
    - criterion
  aoc2020-day3:
    main:                Day3.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
    - criterion
  aoc2020-day4:
    main:                Day4.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
    - criterion
    - unordered-containers
    - text
  aoc2020-day5:
    main:                Day5.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
    - criterion
    - unordered-containers
    - text
  aoc2020-day6:
    main:                Day6.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
    - criterion
    - containers
    - unordered-containers
    - text
  aoc2020-day7:
    main:                Day7.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
    - criterion
    - containers
    - graphite
    - unordered-containers
    - text
    - parsec
  aoc2020-day8:
    main:                Day8.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
    - criterion
    - containers
    - graphite
    - unordered-containers
    - text
    - parsec
    - mtl
  aoc2020-day9:
    main:                Day9.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
    - criterion
    - containers
    - graphite
    - unordered-containers
    - text
    - parsec
    - mtl
  aoc2020-day10:
    main:                Day10.hs
    source-dirs:         app
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
    - criterion
    - containers
    - graphite
    - unordered-containers
    - text
    - parsec
    - mtl

tests:
  aoc2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
    - criterion
